language : python
python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt

script: bash -x test/nosetests_ci-stat.sh

branches :
   only :
     - master
     - dev

after_success:
  - codecov

notifications :
   email :
     - maxwunj@gmail.com
