language : python
python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt

script: nosetests --logging-level=DEBUG --debug=me.maxwu -s -v --with-xunit --xunit-file ./build/circlestat_nose_xunit.xml --with-coverage --cover-package=me.maxwu --cover-html-dir=build/cover --cover-xml-file=build/coverage ./test

branches :
   only :
     - master
     - dev

after_success:
  - codecov

notifications :
   email :
     - maxwunj@gmail.com
