codecov:
  notify:
    require_ci_to_pass: true
  branch: master, dev

comment:
  behavior: default
  layout: header, diff
  require_changes: false

coverage:
  precision: 2
  range: "70..100"
  round: down
  status:
    changes: false
    patch: true
    project: true
  ignore: 
  - doc/.*
  - target/.*
  - build/.*
  - .*/resources/.*
  - doc/.*
  - test/.*
